name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          # Write your CML report
          echo "## Model Metrics" > report.md
          cat metrics_5.txt >> report.md
          cat metrics_10.txt >> report.md
          cat metrics_15.txt >> report.md

          echo '## Viz' >> report.md
          cml-publish residuals_5.png --md >> report.md
          cml-publish residuals_10.png --md >> report.md
          cml-publish residuals_15.png --md >> report.md
          
          cml-send-comment report.md
